In [90]:
#header files
import numpy as np 
import math
from numpy.linalg import lstsq
from scipy.linalg import orth

#getting the number of atoms as the input
global N
N=int(input()) 

#routine to get the S values. S goes from |U-D|/2,......,(U+D)/2, where U and D are the number of upspins and downspins respectively
#when both U and D are equal (if odd, then differ by 1), we would get the full spectrum of values for S
global S
if(N%2==0):
    S_arr=np.arange((N/2)+1)
else:
    S_arr=np.arange(1/2,(N/2)+1,1)


#printing all the states for a given S value
S_in=float(input())
if(S_in>0):
    m_in=np.arange(-S_in,S_in+1)

#this routine will output the corresponding projection matrix given the user input on S.
#ones represent up spin and zeros down spin in the (m1,m2...) basis

#we start with the (S_max,m_max) state, since we know this state in the (m1,m2...) basis
global S_max
S_max=np.max(S_arr)


#number of rows of the matrix
r=2**N
#number of columns
c=(2**N)+2
#the matrix which contains all the states and their corresponding representations in the (m1,m2...) basis
M=np.zeros((r,c))

#filling the first two columns of the matrix with the S and M values. The other columns will contain the projection of this S,m vector along each of the (m1,m2...) bases.
if(N%2==1): 
    for i in range(2*int(S_max)+2):
        M[i][0]=S_max
        M[i][1]=S_max-i

    #filling the state corresponding to the S_max, m_max state
    M[0][c-1]=1
    #print(M)
else:
    for i in range(2*int(S_max)+1):
        M[i][0]=S_max
        M[i][1]=S_max-i

    #filling the state corresponding to the S_max, m_max state
    M[0][c-1]=1
    #print(M)
    

# Function to convert Decimal number  
# to Binary number  
def decimalToBinary(n):  
    return bin(n).replace("0b", "")  

# Function to convert Binary number 
# to Decimal number 
  
def binDec(array):
    sum=0
    for i in range(len(array)):
        sum=sum+2**(len(array)-i-1)*array[i]
    return sum
    

#function which performs the S_minus operation
def S_minus(arr):
    #print(arr)
    s=arr[0]
    m=arr[1]
    n=math.sqrt((s+m)*(s-m+1))
    #psi=np.zeros((c-2))
    psi=arr[2:]
    #print(psi)
    out=np.zeros(len(psi))
    for i in range(len(psi)):
        if(psi[i]==0):
            continue
        else:
            cop=psi[i]
            bino=decimalToBinary(i)
            bin_state=np.array(list(bino), dtype=int)
            #print(np.zeros(N+1-len(bin_state)))
            if(N-len(bin_state)==0):
                #print(N-len(bin_state))
                state=bin_state
            else: 
                #print(N-len(bin_state))
                #print(bin_state)
                state=np.concatenate([np.zeros(N-len(bin_state)),bin_state])
                #print(state)
            for l in range(N):
                test=state.copy()
                if(test[l]==1):
                    test[l]=0
                    num=int(binDec(test))
                    out[num]=out[num]+cop
                else:
                    continue
                
    #print(np.true_divide(out,n))
    return np.true_divide(out,n)
                
                
#filling the other rows by calling a routine which takes in the previous row as its input
#if(N%2==1):
for i in range(1,2*int(S_max)+2):
    M[i,2:]=S_minus(M[i-1,:])
#else:
#    for i in range(1,2*int(S_max)+1):
#        M[i,2:]=S_minus(M[i-1,:])
    

print(M)
#M is a matrix. In each row, the first two elements contain the s value and the m value respectively. The other values 
#in the row contain the corresponding representation in the (m1,m2....) basis and the values represent the projection 
#of this vector in the other basis. E.g: if it has element 1 in the i th row, it's projection along i represented as
#binary, is 1. In the binary code, 1's represent up spin and 0's represent downspin.

3
2
[[ 1.5         1.5         0.          0.          0.          0.
   0.          0.          0.          1.        ]
 [ 1.5         0.5         0.          0.          0.          0.57735027
   0.          0.57735027  0.57735027  0.        ]
 [ 1.5        -0.5         0.          0.57735027  0.57735027  0.
   0.57735027  0.          0.          0.        ]
 [ 1.5        -1.5         1.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]]


In [ ]:
#routine for getting the projection matrix for the S_max subspace
dim=N**2
proj=np.zeros((dim,dim))
i=0
while(M[i][0]==S_max):
    proj=proj+np.outer(M[i,2:],M[i,2:])
    i=i+1
    

In [ ]:
#generating the complete M matrix for other values of S also. Call this matrix P.
#initialising it with zeros of required size
if(N%2==0):
    P=np.zeros(int((S_max+1)**2),2**N+2)
    om=2
else:
    alpha=(((2*S_max)+1)/2) #error_look it up
    rows=int(alpha*(alpha+1))
    P=np.zeros((rows),2**N+2)
    om=1

i=0
#initialising the matrix with the first two columns as s and m.
while(S_max-i>=0):
    S=S_max-i
    for j in range(2*int(S)+om):
        P[j][0]=S
        P[j][1]=S-j
    i=i+1

#function for orthonormalization
def ortho(v,k,length):
    O=np.reshape(v,(k,length))
    O=O.T
    rand_vec = np.random.rand(O.shape[0], 1)
    A = np.hstack((O, rand_vec))
    b = np.zeros(O.shape[1] + 1)
    b[-1] = 1
    vt=lstsq(A.T, b)[0]
    return(vt/linalg.norm(vt))
    
#filling in the matrix with the states

P[0][int(N**2+1)]=1
for i in range(1,int(P.shape[0])):
    if(P[i][0]==P[i][1]):
        v=[]
        for j in range(i):
            k=0 #NO_MULTPLE_STATES_FATAL_ERROR/
            if(P[j][1]==P[i][1]):
                k=k+1
                vec=P[j,2:].copy()
                v=np.append(v,(vec[np.nonzero(vec)[0]]))
        vt=ortho(v,k,len(np.nonzero(vec)[0]))
        vector=P[i,2:]
        vector[np.nonzero(vec)[0]]=vt
    else:
        P[i,2:]=S_minus(P[i-1,:])
       

In [ ]:
maximal S-no problem

(1,1)-how many states are here?
how to do so?
4 states with m=1 in (m1,m2...) basis
if s is 0 m cannot be 1
3 separate (1,1) states
go to complex coefficients?

In [ ]:
#getting the projection matrices
sin=input()
if(math.modf(sin)[0]!=0):
    bin=1
else:
    bin=2

for i in range(int(P.shape[0])):
    if(P[i][0]==sin):
        vmatrix=P[i:i+int(2*sin+bin)][:]
        break


In [ ]:
dim=N**2
proj=np.zeros((dim,dim))
i=0
while(vmatrix[i][0]==sin):
    proj=proj+np.outer(vmatrix[i,2:],vmatrix[i,2:])
    i=i+1
#the final answer!

print(proj)

In [4]:
N=4
S_max=2
r=2**N
#number of columns
c=(2**N)+2
P=np.zeros(int(r),int(c))

i=0
count_1=0
counte=0
#initialising the matrix with the first two columns as s and m.
while(S_max-i>=0):
    count_1=count_1+count
    counte=0
    S=S_max-i
    for j in range(count_1,count_1+(int(2*S)+1)
        counte =counte+1
        P[j][0]=S
        P[j][1]=S-j+count_1
    i=i+1
print(P)

SyntaxError: invalid syntax (<ipython-input-4-dc2302283746>, line 17)

In [8]:
import numpy
A=numpy.zeros((5,5,5))
A[0][0][0]=1
A[0][0][1]=-1
print(A[0,0,2:4])

[0. 0.]


In [63]:
import numpy as np 
import math
from numpy.linalg import lstsq
from scipy.linalg import orth
import cmath
import scipy
from sympy import Matrix
from scipy.linalg import qr
from scipy.linalg import null_space
def ortho(v,k,length):
    O=np.reshape(v,(k,length))
    return(O)
    #print(O.shape)
    b=np.random.random(O.shape[1]) + np.random.random(O.shape[1]) * 1j
    c=np.absolute(b)
    #print(c)
    norm=0
    for i in range(len(c)):
        norm=norm+c[i]**2
    norm=math.sqrt(norm)
    b=b/norm
    #print(norm)
    #print(b)
    e=np.zeros(len(c)-1)
    print(e)
    #O=O.T
    print(O)
    #b=np.linalg.lstsq(O,e)[0]
    #print(d)
    print(b)
    #O=O.T
    #print(O)
    #rand_vec = np.random.rand(O.shape[0], 1)+1j*np.random.rand(O.shape[0], 1)
    #print(rand_vec)
    #A = np.hstack((O, rand_vec))
    #b = np.zeros(O.shape[1] + 1)
    ##b[-1] = 1
    #vt=lstsq(A.T, b)[0]
    #print(O.vt)
    #for i in range(len(vt)):
    #    if(vt[i]<10**-5):
    #        vt[i]=0
    #   else:
    #        continue
    #return(vt)

def null(v,k,length, eps=1e-15):
    A=np.reshape(v,(k,length))
    u, s, vh = scipy.linalg.svd(A)
    null_mask = (s <= eps)
    null_space = scipy.compress(null_mask, vh, axis=0)
    return scipy.transpose(null_space)

def qr_null(v,k,length, tol=None):
    A=np.reshape(v,(k,length))
    Q, R, P = qr(A.T, mode='full', pivoting=True)
    tol = np.finfo(R.dtype).eps if tol is None else tol
    rnk = min(A.shape) - np.abs(np.diag(R))[::-1].searchsorted(tol)
    d=Q[:, rnk:]
    print(A.dot(d))
    c=np.absolute(d)
    #print(c)
    norm=0
    for i in range(len(c)):
        norm=norm+c[i]**2
    norm=math.sqrt(norm)
    d=d/norm
    return d

A=ortho(np.array([1j,0,3j,7,0,1j,0,0,0,0,1j,0],dtype=np.complex128),3,4)
b=null(np.array([1j,0,3j,7,0,1j,0,0,0,0,1j,0],dtype=np.complex128),3,4)
print(b)
#A=np.reshape(np.array([1j,0,0,0,0,1j,0,0,0,0,1j,0]),3,4)
#print(A)
A=Matrix(A)
print(A.nullspace())
#print(b)



[]
[Matrix([
[7.0*I],
[    0],
[    0],
[    1]])]


In [82]:
import numpy as np 
import math
from numpy.linalg import lstsq
from scipy.linalg import orth
import cmath
import scipy
from sympy import Matrix
from scipy.linalg import qr
from scipy.linalg import null_space

def ortho(v,k,length):
    O=np.reshape(v,(k,length))
    return(O)
    #print(O.shape)
    b=np.random.random(O.shape[1]) + np.random.random(O.shape[1]) * 1j
    c=np.absolute(b)
    #print(c)
    norm=0
    for i in range(len(c)):
        norm=norm+c[i]**2
    norm=math.sqrt(norm)
    b=b/norm
    #print(norm)
    #print(b)
    e=np.zeros(len(c)-1)
    print(e)
    #O=O.T
    print(O)
    #b=np.linalg.lstsq(O,e)[0]
    #print(d)
    print(b)
    #O=O.T
    #print(O)
    #rand_vec = np.random.rand(O.shape[0], 1)+1j*np.random.rand(O.shape[0], 1)
    #print(rand_vec)
    #A = np.hstack((O, rand_vec))
    #b = np.zeros(O.shape[1] + 1)
    ##b[-1] = 1
    #vt=lstsq(A.T, b)[0]
    #print(O.vt)
    #for i in range(len(vt)):
    #    if(vt[i]<10**-5):
    #        vt[i]=0
    #   else:
    #        continue
    #return(vt)

A=ortho(np.array([1,0,3j,7,0,1j,0,0,0,0,1j,0],dtype=np.complex128),3,4)
ns=null_space(A)
print(ns[:,0])
print(A.dot(ns))

[-0.98994949-0.j  0.        -0.j  0.        -0.j  0.14142136-0.j]
[[1.22124533e-15+0.j]
 [0.00000000e+00+0.j]
 [0.00000000e+00+0.j]]


In [84]:
S=np.zeros((5,3,2))
print(S)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [109]:
#header files
import numpy as np 
import math
from numpy.linalg import lstsq
from scipy.linalg import orth
import cmath
import scipy
from sympy import Matrix
from scipy.linalg import qr
from scipy.linalg import null_space

#algo
#getting inputs (N and S)
#a 3d matrix with the first matrix containing the vectors for the maximum S and so on.
#find the first matrix using the S- method.
#find the second matrix using the nth roots method.
#start the loop for higher S. in each run of the loop, find the degeneracy for the maximum element (S,S) using an array initialised with all m values and incemented as and when the m value is added. From the previous matrices, find the elements with the m value as S
#send this vector for GSO. Then, apply S_minus to get the matrix elements. 

#pseudocode  
#input (N and S)
#if(N%2==0):
#    S_arr=np.arange((N/2)+1)
#else:
#    S_arr=np.arange(1/2,(N/2)+1,1)

#we start with the (S_max,m_max) state, since we know this state in the (m1,m2...) basis
#global S_max
#S_max=np.max(S_arr)
#all zeros, S_max in height, N**2 rows, N**2+2 columns
#S[0][0][0]=S[0][0][1]=S_max
# #S[0][0][N**2+1]=1 
#for i in range(1,2*S_max+1):
#S[0][i][0]=S_max
#S[0][i][1]=s_max-i
#S[0,i,2:]=S_minus(S[0,i-1,:])
#m=ones(length of (2*Smax+1)/2) if integer, length of S_max:
#m_max=zeros(length of (2*Smax+1)/2) if integer, length of S_max
#m_max[i]=N C (N/2-i) if N is even
#if N is odd, m_max[i]=N C int (N/2-(2*i+1)/2)

#omega=cos(2*pi/5)+i sin(2*pi/5)
#l=0
#p=m_max[N-1]-m[N-1]
#while(m[N-1]<=m_max[N-1]):
#S[1][l][0]=S[1][l][1]=S_max-1
#l=l+1
#omega=omega**l
#S[1,l,2:]=S[0,1,2:]*omega**0 till N-1
#m[N-1]=m[N-1]+1
#all mi's except the last =m[N-1]
#complete this matrix for now

#for later matrices:
#S=S_max-2
#i=2
#while(S>=0):
#degen=m_max[N-i]-m[N-i]

#fn that returns all the vectors as a matrix, with the same m
#for i in range(len(S_array)):
#vec_mat=zeros of specified length
#while(S[i][p][0]==S[i][0][0] and S[i][p][0]!=np.zeros of specified length):
#if(S[i][p][1]==m):
#add S[i,p,2:] as a new row to vec_mat

#p=p+1
#
#p=0
#while(m_max[N-i]-m[N-i]>=0):
#S[i][p][0]=S[i][p][1]=S
#S[i,p,2:]=GSO(that matrix i mentioned above)
#m=S.copy()
#j=1

#while(S-j>=-S):
#S[i][p+j*degen][0]=S
#S[i][p+j*degen][1]=S-j
#S[i,p+j*degen,2:]=S_minus(S[i,p+(j-1)*degen,:])
#j=j+1


#GSO(append this)
#p=p+1
#m[N-i]=m[N-i]+1

#
#S=S-1
#all m is same as m[N-i] 
#i=i+1

#for i in range(len(S_array)):
#if(S[i][0][0]==S):
#mat=zeros of specified size (N**2 * N**2)
#p=0
#while(S[i][p][0]=S and S[i,p.2:]!=np.zeros):
#mat=mat+np.outer(S[i,p,2:],S[i,p,2:])
#p=p+1


#final matrix: print(mat)

#FINAL CODE
#functions
# Function to convert Decimal number  
# to Binary number  
def decimalToBinary(n):  
    return bin(n).replace("0b", "")  

# Function to convert Binary number 
# to Decimal number 
  
def binDec(array):
    sum=0
    for i in range(len(array)):
        sum=sum+2**(len(array)-i-1)*array[i]
    return sum
    

#function which performs the S_minus operation
def S_minus(arr):
    #print(arr)
    s=arr[0]
    m=arr[1]
    n=math.sqrt((s+m)*(s-m+1))
    #psi=np.zeros((c-2))
    psi=arr[2:]
    #print(psi)
    out=np.zeros(len(psi))
    for i in range(len(psi)):
        if(psi[i]==0):
            continue
        else:
            cop=psi[i]
            bino=decimalToBinary(i)
            bin_state=np.array(list(bino), dtype=int)
            #print(np.zeros(N+1-len(bin_state)))
            if(N-len(bin_state)==0):
                #print(N-len(bin_state))
                state=bin_state
            else: 
                #print(N-len(bin_state))
                #print(bin_state)
                state=np.concatenate([np.zeros(N-len(bin_state)),bin_state])
                #print(state)
            for l in range(N):
                test=state.copy()
                if(test[l]==1):
                    test[l]=0
                    num=int(binDec(test))
                    out[num]=out[num]+cop
                else:
                    continue
                
    #print(np.true_divide(out,n))
    return np.true_divide(out,n)

global N
global S
N=int(input())
S=float(input())


if(N%2==0):
    S_arr=np.arange((N/2)+1)
else:
    S_arr=np.arange(1/2,(N/2)+1,1)

#print(S_arr)
global S_max
S_max=np.max(S_arr)

#3D matrix
S=np.zeros((int(S_max),int(2**N),int(2**N+2)))

#initialising the max state
S[0][0][0]=S_max
S[0][0][1]=S_max
S[0][0][int(2**N+1)]=1

#first matrix
for i in range(1,int(2*S_max+1)):
    S[0][i][0]=S_max
    S[0][i][1]=S_max-i
    S[0,i,2:]=S_minus(S[0,i-1,:])
print(S)

2
1
[[[ 1.          1.          0.          0.          0.
    1.        ]
  [ 1.          0.          0.          0.70710678  0.70710678
    0.        ]
  [ 1.         -1.          1.          0.          0.
    0.        ]
  [ 0.          0.          0.          0.          0.
    0.        ]]]
