In [4]:
#header files
import numpy as np 
import math
from numpy.linalg import lstsq
from scipy.linalg import orth

#getting the number of atoms as the input
global N
N=int(input()) 

#routine to get the S values. S goes from |U-D|/2,......,(U+D)/2, where U and D are the number of upspins and downspins respectively
#when both U and D are equal (if odd, then differ by 1), we would get the full spectrum of values for S
global S
if(N%2==0):
    S_arr=np.arange((N/2)+1)
else:
    S_arr=np.arange(1/2,(N/2)+1,1)


#printing all the states for a given S value
S_in=float(input())
if(S_in>0):
    m_in=np.arange(-S_in,S_in+1)

#this routine will output the corresponding projection matrix given the user input on S.
#ones represent up spin and zeros down spin in the (m1,m2...) basis

#we start with the (S_max,m_max) state, since we know this state in the (m1,m2...) basis
global S_max
S_max=np.max(S_arr)


#number of rows of the matrix
r=2**N
#number of columns
c=(2**N)+2
#the matrix which contains all the states and their corresponding representations in the (m1,m2...) basis
M=np.zeros((r,c))

#filling the first two columns of the matrix with the S and M values. The other columns will contain the projection of this S,m vector along each of the (m1,m2...) bases.
if(N%2==1): 
    for i in range(2*int(S_max)+2):
        M[i][0]=S_max
        M[i][1]=S_max-i

    #filling the state corresponding to the S_max, m_max state
    M[0][c-1]=1
    #print(M)
else:
    for i in range(2*int(S_max)+1):
        M[i][0]=S_max
        M[i][1]=S_max-i

    #filling the state corresponding to the S_max, m_max state
    M[0][c-1]=1
    #print(M)
    

# Function to convert Decimal number  
# to Binary number  
def decimalToBinary(n):  
    return bin(n).replace("0b", "")  

# Function to convert Binary number 
# to Decimal number 
  
def binDec(array):
    sum=0
    for i in range(len(array)):
        sum=sum+2**(len(array)-i-1)*array[i]
    return sum
    

#function which performs the S_minus operation
def S_minus(arr):
    #print(arr)
    s=arr[0]
    m=arr[1]
    n=math.sqrt((s+m)*(s-m+1))
    #psi=np.zeros((c-2))
    psi=arr[2:]
    #print(psi)
    out=np.zeros(len(psi))
    for i in range(len(psi)):
        if(psi[i]==0):
            continue
        else:
            cop=psi[i]
            bino=decimalToBinary(i)
            bin_state=np.array(list(bino), dtype=int)
            #print(np.zeros(N+1-len(bin_state)))
            if(N-len(bin_state)==0):
                #print(N-len(bin_state))
                state=bin_state
            else: 
                print(N-len(bin_state))
                #print(bin_state)
                state=np.concatenate([np.zeros(N-len(bin_state)),bin_state])
                #print(state)
            for l in range(N):
                test=state.copy()
                if(test[l]==1):
                    test[l]=0
                    num=int(binDec(test))
                    out[num]=out[num]+cop
                else:
                    continue
                
    return np.true_divide(out,n)
                
                
#filling the other rows by calling a routine which takes in the previous row as its input
#if(N%2==1):
#    for i in range(1,2*int(S_max)+2):
M[i,2:]=S_minus(M[i-1,:])
#else:
#    for i in range(1,2*int(S_max)+1):
#        M[i,2:]=S_minus(M[i-1,:])
    

print(M)
#M is a matrix. In each row, the first two elements contain the s value and the m value respectively. The other values 
#in the row contain the corresponding representation in the (m1,m2....) basis and the values represent the projection 
#of this vector in the other basis. E.g: if it has element 1 in the i th row, it's projection along i represented as
#binary, is 1. In the binary code, 1's represent up spin and 0's represent downspin.

4
2
[[ 2.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2. -2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.

In [ ]:
#routine for getting the projection matrix for the S_max subspace
dim=N**2
proj=np.zeros((dim,dim))
i=0
while(M[i][0]==S_max):
    proj=proj+np.outer(M[i,2:],M[i,2:])
    i=i+1
    

In [ ]:
#generating the complete M matrix for other values of S also. Call this matrix P.
#initialising it with zeros of required size
if(N%2==0):
    P=np.zeros(int((S_max+1)**2),2**N+2)
    om=2
else:
    alpha=(((2*S_max)+1)/2)
    rows=int(alpha*(alpha+1))
    P=np.zeros((rows),2**N+2)
    om=1

i=0
#initialising the matrix with the first two columns as s and m.
while(S_max-i>=0):
    S=S_max-i
    for j in range(2*int(S)+om):
        P[j][0]=S
        P[j][1]=S-j
    i=i+1

#function for orthonormalization
def ortho(v,k,length):
    O=np.reshape(v,(k,length))
    O=O.T
    rand_vec = np.random.rand(O.shape[0], 1)
    A = np.hstack((O, rand_vec))
    b = np.zeros(O.shape[1] + 1)
    b[-1] = 1
    vt=lstsq(A.T, b)[0]
    return(vt/linalg.norm(vt))
    
#filling in the matrix with the states

P[0][int(N**2+1)]=1
for i in range(1,int(P.shape[0])):
    if(P[i][0]==P[i][1]):
        v=[]
        for j in range(i):
            k=0
            if(P[j][1]==P[i][1]):
                k=k+1
                vec=P[j,2:].copy()
                v=np.append(v,(vec[np.nonzero(vec)[0]]))
        vt=ortho(v,k,len(np.nonzero(vec)[0]))
        vector=P[i,2:]
        vector[np.nonzero(vec)[0]]=vt
    else:
        P[i,2:]=S_minus(P[i-1,:])
       

In [ ]:
#getting the projection matrices
sin=input()
if(math.modf(sin)[0]!=0):
    bin=1
else:
    bin=2

for i in range(int(P.shape[0])):
    if(P[i][0]==sin):
        vmatrix=P[i:i+int(2*sin+bin)][:]
        break


In [ ]:
dim=N**2
proj=np.zeros((dim,dim))
i=0
while(vmatrix[i][0]==sin):
    proj=proj+np.outer(vmatrix[i,2:],vmatrix[i,2:])
    i=i+1
#the final answer!
print(proj)